video_behavior:
  _target_: omnimouse.masking.MaskingStrategy
  n_visible_neurons: 0
  prefix_start_idx: 0
  prefix_len: 0
  full_population_prefix_len: 0
  response_context_start_idx: 0
  max_response_context_samples: 0
  max_n_reconstructed_neurons: 4096
  suffix_start_idx: 30
  suffix_len: 30
  n_visible_frames_start_idx: 0
  n_visible_frames: 60
  behavior_encoded: true
  behavior_reconstructed: false
  weight: 1.0
stimulus_driven:
  _target_: omnimouse.masking.MaskingStrategy
  n_visible_neurons: 0
  prefix_start_idx: 0
  prefix_len: 0
  full_population_prefix_len: 0
  response_context_start_idx: 0
  max_response_context_samples: 0
  max_n_reconstructed_neurons: 4096
  suffix_start_idx: 30
  suffix_len: 30
  n_visible_frames_start_idx: 0
  n_visible_frames: 60
  behavior_encoded: false
  behavior_reconstructed: false
  weight: 1.0
causal_response_behavior:
  _target_: omnimouse.masking.MaskingStrategy
  n_visible_neurons: 4096
  prefix_start_idx: 0
  prefix_len: 25
  full_population_prefix_len: 0
  response_context_start_idx: 0
  max_response_context_samples: 60
  max_n_reconstructed_neurons: 4096
  suffix_start_idx: 30
  suffix_len: 30
  n_visible_frames_start_idx: 0
  n_visible_frames: 0
  behavior_encoded: true
  behavior_reconstructed: false
  weight: 1.0
all_response_only:
  _target_: omnimouse.masking.MaskingStrategy
  n_visible_neurons: 4096
  prefix_start_idx: 0
  prefix_len: 60
  full_population_prefix_len: 0
  response_context_start_idx: 0
  max_response_context_samples: 60
  max_n_reconstructed_neurons: 0
  suffix_start_idx: 0
  suffix_len: 0
  n_visible_frames_start_idx: 0
  n_visible_frames: 0
  behavior_encoded: false
  behavior_reconstructed: true
  weight: 1.0
population_1024_response_behavior:
  _target_: omnimouse.masking.MaskingStrategy
  n_visible_neurons: 1024
  prefix_start_idx: 0
  prefix_len: 60
  full_population_prefix_len: 0
  response_context_start_idx: 0
  max_response_context_samples: 60
  max_n_reconstructed_neurons: 3072
  suffix_start_idx: 30
  suffix_len: 30
  n_visible_frames_start_idx: 0
  n_visible_frames: 0
  behavior_encoded: true
  behavior_reconstructed: false
  weight: 1.0
population_1024_response_video_behavior:
  _target_: omnimouse.masking.MaskingStrategy
  n_visible_neurons: 1024
  prefix_start_idx: 30
  prefix_len: 30
  full_population_prefix_len: 0
  response_context_start_idx: 30
  max_response_context_samples: 30
  max_n_reconstructed_neurons: 3072
  suffix_start_idx: 30
  suffix_len: 30
  n_visible_frames_start_idx: 30
  n_visible_frames: 30
  behavior_encoded: true
  behavior_reconstructed: false
  weight: 1.0
causal_response_video_behavior:
  _target_: omnimouse.masking.MaskingStrategy
  n_visible_neurons: 4096
  prefix_start_idx: 0
  prefix_len: 25
  full_population_prefix_len: 0
  response_context_start_idx: 0
  max_response_context_samples: 30
  max_n_reconstructed_neurons: 4096
  suffix_start_idx: 30
  suffix_len: 30
  n_visible_frames_start_idx: 30
  n_visible_frames: 30
  behavior_encoded: true
  behavior_reconstructed: false
  weight: 1.0
invpopcaus_response_video_behavior:
  _target_: omnimouse.masking.MaskingStrategy
  n_visible_neurons: 1024
  prefix_start_idx: 10
  prefix_len: 40
  full_population_prefix_len: 15
  response_context_start_idx: 10
  max_response_context_samples: 40
  max_n_reconstructed_neurons: 3072
  suffix_start_idx: 30
  suffix_len: 30
  n_visible_frames_start_idx: 40
  n_visible_frames: 20
  behavior_encoded: true
  behavior_reconstructed: false
  weight: 1.0